#ifndef OXS_CONFIG_ADVANCED_h
#define OXS_CONFIG_ADVANCED_h

#define PIN_SERIALTX 4

#define REFERENCE_VOLTAGE 3300

#define PIN_VOLTAGE  1
#define RESISTOR_TO_GROUND 13.0
#define RESISTOR_TO_VOLTAGE 68.0
#define OFFSET_VOLTAGE 44.213
#define SCALE_VOLTAGE 0.8438

#define PIN_CURRENTSENSOR 2
#define MVOLT_AT_ZERO_AMP 0.0
#define MVOLT_PER_AMP     99.051
#define RESISTOR_TO_GROUND_FOR_CURRENT 0.0
#define RESISTOR_TO_CURRENT_SENSOR     0.0

#endif
