#ifndef OXS_CONFIG_BASIC_h
#define OXS_CONFIG_BASIC_h


#define PROTOCOL FRSKY_HUB

#define VFAS_SOURCE VOLT_1

#define FIRST_BARO_SENSOR_USE BMP280
#define VSPEED_SOURCE FIRST_BARO

#define AIRSPEED_SENSOR_USE NO_AIRSPEED

#define ARDUINO_MEASURES_VOLTAGES   YES

#define ARDUINO_MEASURES_A_CURRENT YES

#define AN_ADS1115_IS_CONNECTED NO

#define CALCULATE_RPM NO

#define SAVE_TO_EEPROM NO

#define A_GPS_IS_CONNECTED NO

#define A_MPU6050_IS_CONNECTED NO

#define CALCULATE_YAW_WITH_HMC5883 NO

#define A_FLOW_SENSOR_IS_CONNECTED   NO

#define A_LOCATOR_IS_CONNECTED   NO

#endif
